Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

Problem Statement 2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [1]:
def geoprog(input_vector,n,increasing):
    if ((type(n)==int) and (increasing==True or increasing==False) and 
        (type(input_vector)==list or type(input_vector)==tuple)):
        import numpy as np
        length=len(input_vector)
        matrix = np.ones((length,n),dtype=int)
        if increasing==False:
            i=0
            for ele in range(n-1,0,-1): 
                for ele1 in range(1,length+1):
                    matrix[ele1-1][i]=input_vector[ele1-1]**ele
                i+=1
        else:
            for ele in range(0,n-1): 
                for ele1 in range(1,length+1):
                    matrix[ele1-1][ele+1]=input_vector[ele1-1]**(ele+1)
    return matrix
#example:-
print(geoprog([0,1,2,3],5,increasing=True))
print("-------------------------------------")
print(geoprog([0,1,2,3],5,increasing=False))

[[ 1  0  0  0  0]
 [ 1  1  1  1  1]
 [ 1  2  4  8 16]
 [ 1  3  9 27 81]]
-------------------------------------
[[ 0  0  0  0  1]
 [ 1  1  1  1  1]
 [16  8  4  2  1]
 [81 27  9  3  1]]


In [2]:
def movavg(arr,k):
  import numpy as np
  n=len(arr)
  res=[]
  for ele in range(n-k+1):
      i=ele;s=0
      for ele1 in range(k):
          s=s+arr[i]
          i+=1
      s=s/k  
      res.append(round(s,2))
  return np.array(res)

In [4]:
import numpy as np
data = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3
movavg(data,k)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])